# Generated by Django 2.0.5 on 2018-09-10 11:16

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='نام نوینده')),
                ('decs', models.CharField(max_length=200, verbose_name='توضیحات')),
                ('authorPic', models.ImageField(default='/Author/Author.jpg', storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\iman\\Desktop\\bookbiar\\site\\prjbrji\\Statics'), upload_to='Authors', verbose_name='تصویر')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\iman\\Desktop\\bookbiar\\site\\prjbrji\\Statics'), upload_to='Banner', verbose_name='تصویر')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='توضیحات')),
                ('link', models.GenericIPAddressField(verbose_name='لینک')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='عنوان')),
                ('subject', models.CharField(max_length=100, verbose_name='موضوع')),
                ('code', models.CharField(max_length=13, unique=True, verbose_name='شابک')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(default='/Book/', storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\iman\\Desktop\\bookbiar\\site\\prjbrji\\Statics'), upload_to='Books', verbose_name='تصویر')),
                ('Dakheli', models.CharField(blank=True, default='NULL', max_length=20, verbose_name='داخلی')),
                ('Gostaresh', models.CharField(blank=True, default='NULL', max_length=20, verbose_name='گسترش')),
                ('Ghoghnus', models.CharField(blank=True, default='NULL', max_length=20, verbose_name='ققنوس')),
                ('Asar', models.CharField(blank=True, default='NULL', max_length=20, verbose_name='اثار')),
                ('GitaMehr', models.CharField(blank=True, default='NULL', max_length=20, verbose_name='گیتا مهر')),
                ('Elias', models.CharField(blank=True, default='NULL', max_length=20, verbose_name='الیاس')),
                ('PezeshkiPasargad', models.CharField(blank=True, default='NULL', max_length=20, verbose_name='پاسارگاد')),
                ('PaiamNur', models.CharField(blank=True, default='NULL', max_length=20, verbose_name='پیام نور')),
                ('Jungle', models.CharField(blank=True, default='NULL', max_length=20, verbose_name='جنگل')),
                ('Bidgol', models.CharField(blank=True, default='NULL', max_length=20, verbose_name='بیدگل')),
                ('GotenBerg', models.CharField(blank=True, default='NULL', max_length=20, verbose_name='گتنبرگ')),
                ('Kharazmi', models.CharField(blank=True, default='NULL', max_length=20, verbose_name='خوارزمی')),
                ('SimaieDanesh', models.CharField(blank=True, default='NULL', max_length=20, verbose_name='سیمای دانش')),
                ('inventory', models.BooleanField(default=False, verbose_name='موجودی')),
                ('price', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='قیمت')),
                ('printNumber', models.IntegerField(blank=True, null=True, verbose_name='نوبت چاپ')),
                ('publishYear', models.CharField(blank=True, max_length=4, null=True, verbose_name='سال چاپ')),
                ('created_time', models.DateField(editable=False)),
                ('updated_time', models.DateField(editable=False)),
                ('language', models.SmallIntegerField(choices=[(0, 'فارسی'), (1, 'انگلیسی'), (2, 'غیره')], default=0, verbose_name='زبان کتاب')),
                ('ghat', models.SmallIntegerField(choices=[(0, 'رقعی'), (1, 'وزیری'), (2, 'وزیری جدید'), (3, 'پالتویی'), (4, 'رحلی'), (5, 'خشتی'), (6, 'جیبی')], default=0, verbose_name='قطع')),
                ('jeld', models.SmallIntegerField(choices=[(0, 'شومیز'), (1, 'گالینگور'), (2, 'سلفونی')], default=0, verbose_name='نوع جلد')),
                ('pages', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='تعداد صفحه')),
                ('weight', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='وزن')),
                ('likes', models.IntegerField(default=0, verbose_name='پسندیدم ها')),
                ('dilikes', models.IntegerField(default=0, verbose_name='نپسندیدم ها')),
                ('views', models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='بازدید')),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='تخفیف')),
                ('sales', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=4, verbose_name='تعداد فروش')),
                ('available', models.BooleanField(default=True, verbose_name='قابل خرید')),
                ('visiblity', models.BooleanField(default=True, verbose_name='نمایش')),
                ('stock', models.DecimalField(decimal_places=0, default=4, max_digits=2, verbose_name='قابل خرید')),
            ],
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام')),
                ('books', models.ManyToManyField(to='books.Book', verbose_name='کتاب ها')),
            ],
        ),
        migrations.CreateModel(
            name='Categori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoriName', models.CharField(max_length=30, verbose_name='نام')),
                ('catStatus', models.SmallIntegerField(choices=[(0, 'دسته اصلی'), (1, 'زیر دسته 1'), (2, 'زیر دسته 2')], default=0, verbose_name='نوع دسته')),
                ('subCat', models.ManyToManyField(blank=True, related_name='_categori_subCat_+', to='books.Categori', verbose_name='زیر دسته ها')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام')),
                ('decs', models.CharField(max_length=200, verbose_name='توضیحات')),
                ('publisherPic', models.ImageField(default='/Publisher/Publisher.jpg', storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\iman\\Desktop\\bookbiar\\site\\prjbrji\\Statics'), upload_to='Publisher', verbose_name='تصویر')),
            ],
        ),
        migrations.CreateModel(
            name='topCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\iman\\Desktop\\bookbiar\\site\\prjbrji\\Statics'), upload_to='Banner', verbose_name='تصویر')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='نام مترجم')),
                ('decs', models.CharField(max_length=200, verbose_name='توضیحات')),
                ('translatorPic', models.ImageField(default='/Translator/Translator.jpg', storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\iman\\Desktop\\bookbiar\\site\\prjbrji\\Statics'), upload_to='Translator', verbose_name='تصویر')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Publisher', verbose_name='ناشر'),
        ),
        migrations.AddField(
            model_name='book',
            name='secondCat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second', to='books.Categori', verbose_name='دسته فرعی'),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='book',
            name='thirdCat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third', to='books.Categori', verbose_name='دسته فرعی دوم'),
        ),
        migrations.AddField(
            model_name='book',
            name='translator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Translator', verbose_name='مترجم'),
        ),
        migrations.AddField(
            model_name='book',
            name='typeId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='main', to='books.Categori', verbose_name='نوع محصول'),
        ),
        migrations.AddField(
            model_name='book',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Author', verbose_name='نویسنده'),
        ),
    ]
