# Generated by Django 2.0.5 on 2018-09-24 15:42

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0003_auto_20180917_1333'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(default='NULL', max_length=11)),
                ('address', models.CharField(default='NULL', max_length=300)),
                ('postCode', models.CharField(default='NULL', max_length=10)),
                ('city', models.CharField(blank=True, max_length=25)),
                ('country', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='card',
            fields=[
                ('orderDate', models.DateField(null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'در سبد خرید'), (2, 'در حال بررسی'), (1, 'سفارش ثبت شده'), (3, 'ارسال شده'), (4, 'برداخت موفق'), (6, 'عدم پرداخت'), (5, 'برداخت ناموفق')], default=0)),
                ('postCode', models.CharField(blank=True, max_length=20)),
                ('userAddrId', models.SmallIntegerField(default=-1)),
                ('postId', models.SmallIntegerField(default=0)),
                ('cardId', models.CharField(default=user.models.getCardId, editable=False, max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='cardItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quanity', models.DecimalField(decimal_places=0, default=1, max_digits=3)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
                ('itemCard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.card')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invCode', models.CharField(default='NULL', max_length=20)),
                ('name', models.CharField(default='NULL', max_length=20)),
                ('lastName', models.CharField(default='NULL', max_length=15)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('profileImg', models.ImageField(blank=True, default='/media/default.png', storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\iman\\Desktop\\bookbiar\\site\\prjbrji'), upload_to='C:\\Users\\iman\\Desktop\\bookbiar\\site\\prjbrji\\Statics\\media')),
                ('phoneNumber', models.CharField(max_length=11)),
                ('credit', models.DecimalField(decimal_places=0, default=0, max_digits=7)),
                ('isFullUser', models.BooleanField(default=False)),
                ('Gender', models.SmallIntegerField(choices=[(0, 'مرد'), (1, 'زن')], default=0)),
                ('birthDay', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=2)),
                ('birthMonth', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=2)),
                ('mirthYear', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=4)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile'),
        ),
        migrations.AddField(
            model_name='address',
            name='userProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile'),
        ),
    ]
