# Generated by Django 2.0.5 on 2018-09-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='TransId',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'در سبد خرید'), (2, 'در حال بررسی'), (1, 'سفارش ثبت شده'), (3, 'اماده پرداخت'), (4, 'برداخت موفق'), (6, 'عدم پرداخت'), (5, 'برداخت ناموفق'), (7, 'ارسال شده')], default=0),
        ),
    ]
