# Generated by Django 2.0.5 on 2018-09-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180925_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='discountCodePrice',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='carditem',
            name='allBookDiscountPrice',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, verbose_name='تخفیف قیمت پرداختی'),
        ),
        migrations.AddField(
            model_name='carditem',
            name='allBookPayedPrice',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, verbose_name='قیمت پرداخت شده'),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'در سبد خرید'), (1, 'در حال بررسی'), (2, 'اماده پرداخت'), (3, 'برداخت موفق'), (5, 'عدم پرداخت'), (4, 'برداخت ناموفق'), (6, 'ارسال شده')], default=0),
        ),
    ]
